env:
  global:
  - PACKER_VERSION=1.0.0
  - TERRAFORM_VERSION=0.9.8
  - TOOLS_DIR=$HOME/tools
  - PACKER_TEMPLATE=packer_apache_php.json
  - PACKER_VARS=vars/travis.json
  - STATE_BUCKET=tfstates
  - STATE_KEY=demo/frontends
  - AWS_DEFAULT_REGION=eu-west-1
  - secure: "AwcoSpicW5B+4g9jUoIdvVljyV6V5UXgiRqBcOmsFi2fXx+vU3jRtgIJEnu7kPtGMS9Nl0UM4YUAh8WbTPLX4zQn5pvpJIZOfcM/qUYYJWSNmIFtDYWyz6FydU/eX99WeeFNlDGl/nBkdGw8ytFgIjeoBdlfkgdiwosVlrtCU8Xby9XKQNPuLB4ipmtUrewT4ydX5cA2tAX06u7lQKnC2moLhknbg+6eTSUAQBNHCzpwrbBG2ag6RsnKr1kHVtXL89wDB2VN2XQnIzRsM1whypGiCvveWy8E4MDQjeNtcLFZZbuhCvl6QGJ3NCvkyOdZmGu/pKZF9dbUEKZHr5uH7IZb6mWui2fZBAkOK5c2yMKhzUh9Pw8BwXV5kLav2xZ6lMa7axigo15BA7eZot2m84nAXqzGWDRyLP3KTRPRHLWTq7wHomwO07OY7eSfEmH6ITJBwSuOq0ukVebtV9gBooTKC2V6Gn9jeU1/5l+R4nf7mAF6y40f/wsM/QOqplzs31xJNtvxF647h0Uy5rT7oZyEDMZTzVaNo8/nww0sWivHgybiED+uB63mkvB/9aW/4DYBPB5dxisGYz8lQGgEzPAMXUg5C+cYuxMAN98/e8l9oEWfdnZLQlDKxpA7u5dq4vIPfuplC5MaEk6XnKgn6W4lvZAimVB/xjuPUGVLcUI="
  - secure: "JK6SaUmZWu/mn/pi/t560QIR+8dQiK2eDXCm/fdrfUOa0NOMkwhvJ6RMfW5smu5PyWFGBqXTIur0e8vckvocE5D4GcK+EBLwj+GKtVIw+q2JlS/hfkaxX4m0PLPX5y8w3QeJHDqchQF6WdYq/lVPlD/3qo0QHaznl3767vqzOR8R14S8DwuKcHph4jgHtT47nWb71c8FnhRVjZzDF7FKYfP1M3kW0mT7MeSL5jDxtKmoYNInMyy85ZJan8sFueAzryTnZa2NHcsycoLyUTKoW33ft1dHvwpa+oVMuz26W6kxPxd+A2iEzlIpPf5Sp05yKq6fda6YouFckOpwtfJhg5AxPu75/DRMqA3fqljxxhAUvue33v1PZeNyhW+9uP9Xg+3QKTdNBf/FAiu/msQcfnVobmbVMBjuPexfChqS5P48ATYYD5ibXRVCfbxEZmKETSGFfKG41+23kcfrq3PXqVYnJe261PmREA6aCZjZisaDGOpdQ446gJ2/NtfSPY6CBdd3/IvV8dXGrvZ/DhmBhpU7zcWWwbczu9xYMnWHTG8QZ2LrtLAvTJDbkC3JsiJGMl9XB2GX9CfMGCESr5f23lWS/AdxXsvYt/c6GzgR/aYDSLNUXYxzAfD6aLoJxSH5EPRLRkjBGF4j9A1tQ4z8yiQbnzLd0yElB0jEP3pnj1s="


dist: trusty

language: php

php:
  - '5.6'

before_install:
  - composer self-update

script:
  - php -l site/index.php
  - export COMMIT_SUBJECT="$(git log --format=%s --no-merges -n 1)"

before_deploy:
  - export PATH=$PATH:$TOOLS_DIR/bin
  - scripts/install_packer.sh
  - scripts/install_terraform.sh
#  - pip install --user awscli

deploy:
  provider: script
  script:
    - scripts/pack_and_deploy.sh $TRAVIS_BUILD_DIR $PACKER_VARS $PACKER_TEMPLATE $TRAVIS_COMMIT $STATE_BUCKET $STATE_KEY
  on:
    branch: master
    condition: "$COMMIT_SUBJECT != *\"[no deploy]\"*"
